"""Eliminar campo contrasena

Revision ID: 5618bb762fb9
Revises: ec3b1680c084
Create Date: 2026-06-18 13:55:43.808807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5618bb762fb9'
down_revision = 'ec3b1680c084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('contrasena')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', mysql.VARCHAR(length=150), nullable=False))

    # ### end Alembic commands ###
